# Generated by Django 3.0.2 on 2020-11-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=14)),
                ('value', models.CharField(max_length=1400)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlanetaKino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('posterIMG', models.CharField(max_length=140)),
                ('href', models.CharField(max_length=140)),
                ('date', models.CharField(max_length=20)),
                ('inTheater', models.BooleanField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
