# Generated by Django 3.0.2 on 2020-11-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('title_full', models.CharField(max_length=140, null=True)),
                ('href', models.CharField(max_length=420)),
                ('href_title', models.CharField(max_length=420, null=True)),
                ('emojis', models.CharField(max_length=7, null=True)),
                ('filter', models.CharField(max_length=140, null=True)),
                ('delay', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='feedUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('href', models.CharField(max_length=420)),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=42)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
