# Generated by Django 3.1.3 on 2021-03-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedUpdate', '0002_auto_20210207_2006'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedupdate',
            index=models.Index(fields=['title'], name='feedUpdate__title_f39d3b_idx'),
        ),
    ]
