# Generated by Django 3.0.2 on 2020-11-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('title_full', models.CharField(max_length=140)),
                ('href', models.CharField(max_length=420)),
                ('emojis', models.CharField(max_length=14, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('description', models.CharField(max_length=420, null=True)),
                ('calendar', models.CharField(max_length=42)),
                ('href', models.CharField(max_length=420, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
